### ISSUE TITLE
error: Package ‘async-’ is unavailable

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#951] opened 2021-09-29 02:11 UTC
after choosing the china elpa 

```Warning (initialization): An error occurred while loading ‘c:/soft/soft_install/msys2/home/kk/.emacs.d/init.el’:
error: Package ‘async-’ is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

**Comment by redguardtoo** [comment] 2021-09-29 07:46
Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

**Comment by Bobeemer** [comment] 2021-10-01 11:08
I also have this problem,but there is no problem when opening the emacs update after failure, this is the problem is display.
Environment: ArchLinux
Problem:
Debugger entered--Lisp error: (file-error "https://mirrors.163.com/elpa/melpa-stable/archive-..." "Not found")
  signal(file-error ("https://mirrors.163.com/elpa/melpa-stable/archive-..." "Not found"))
  package--with-response-buffer-1("https://mirrors.163.com/elpa/melpa-stable/" #f(compiled-function () #<bytecode 0x157fb7720641>) :file "archive-contents" :async nil :error-function #f(compiled-function () #<bytecode 0x157fb7720659>) :noerror nil)
  package--download-one-archive(("melpa-stable" . "https://mirrors.163.com/elpa/melpa-stable/") "archive-contents" nil)
  package--download-and-read-archives(nil)
  package-refresh-contents()
  (cond ((package-installed-p package min-version) t) ((or (assoc package package-archive-contents) no-refresh) (package-install package)) (t (package-refresh-contents) (require-package package min-version t)))
  require-package(async)
  eval-buffer(#<buffer  *load*-658824> nil "/home/yfc/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 8884
  load-with-code-conversion("/home/yfc/.emacs.d/lisp/init-elpa.el" "/home/yfc/.emacs.d/lisp/init-elpa.el" t t)
  load("/home/yfc/.emacs.d/lisp/init-elpa" t t)
  (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t))
  (if (or (not maybe-disabled) (not (my-vc-merge-p))) (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t)))
  require-init(init-elpa)
  (let* ((file-name-handler-alist nil)) (require-init 'init-autoload) (require-init 'init-modeline) (require-init 'init-utils) (require-init 'init-file-type) (require-init 'init-elpa) (if my-disable-idle-timer (progn (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir)))) (require-init 'init-spelling t) (require-init 'init-ibuffer t) (require-init 'init-ivy) (require-init 'init-windows) (require-init 'init-javascript t) (require-init 'init-org t) (require-init 'init-python t) (require-init 'init-lisp t) (require-init 'init-yasnippet t) (require-init 'init-cc-mode t) (require-init 'init-linum-mode) (require-init 'init-git) (require-init 'init-gtags t) (require-init 'init-clipboard) (require-init 'init-ctags t) (require-init 'init-bbdb t) (require-init 'init-gnus t) (require-init 'init-lua-mode t) (require-init 'init-workgroups2 t) (require-init 'init-term-mode t) (require-init 'init-web-mode t) (require-init 'init-company t) (require-init 'init-chinese t) (require-init 'init-keyfreq t) (require-init 'init-httpd t) (require-init 'init-theme) (require-init 'init-essential) (require-init 'init-misc t) (require-init 'init-emacs-w3m t) (require-init 'init-shackle t) (require-init 'init-dired t) (require-init 'init-writting t) (require-init 'init-hydra) (require-init 'init-evil) (require-init 'init-ediff) (if my-disable-idle-timer nil (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir))) (require-init 'init-flymake t) (if (my-vc-merge-p) nil (setq custom-file (expand-file-name (concat my-emacs-d "custom-set-variables.el"))) (if (file-exists-p custom-file) (load custom-file t t)) (load (expand-file-name "~/.custom.el") t nil)))
  eval-buffer(#<buffer  *load*> nil "/home/yfc/.emacs.d/init.el" nil t)  ; Reading at buffer position 6035
  load-with-code-conversion("/home/yfc/.emacs.d/init.el" "/home/yfc/.emacs.d/init.el" t t)
  load("/home/yfc/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x157fb6e69529>) #f(compiled-function () #<bytecode 0x157fb6e69541>) t)
  command-line()
  normal-top-level()Debugger entered--Lisp error: (file-error "https://mirrors.163.com/elpa/melpa-stable/archive-..." "Not found")
  signal(file-error ("https://mirrors.163.com/elpa/melpa-stable/archive-..." "Not found"))
  package--with-response-buffer-1("https://mirrors.163.com/elpa/melpa-stable/" #f(compiled-function () #<bytecode 0x157fb7720641>) :file "archive-contents" :async nil :error-function #f(compiled-function () #<bytecode 0x157fb7720659>) :noerror nil)
  package--download-one-archive(("melpa-stable" . "https://mirrors.163.com/elpa/melpa-stable/") "archive-contents" nil)
  package--download-and-read-archives(nil)
  package-refresh-contents()
  (cond ((package-installed-p package min-version) t) ((or (assoc package package-archive-contents) no-refresh) (package-install package)) (t (package-refresh-contents) (require-package package min-version t)))
  require-package(async)
  eval-buffer(#<buffer  *load*-658824> nil "/home/yfc/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 8884
  load-with-code-conversion("/home/yfc/.emacs.d/lisp/init-elpa.el" "/home/yfc/.emacs.d/lisp/init-elpa.el" t t)
  load("/home/yfc/.emacs.d/lisp/init-elpa" t t)
  (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t))
  (if (or (not maybe-disabled) (not (my-vc-merge-p))) (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t)))
  require-init(init-elpa)
  (let* ((file-name-handler-alist nil)) (require-init 'init-autoload) (require-init 'init-modeline) (require-init 'init-utils) (require-init 'init-file-type) (require-init 'init-elpa) (if my-disable-idle-timer (progn (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir)))) (require-init 'init-spelling t) (require-init 'init-ibuffer t) (require-init 'init-ivy) (require-init 'init-windows) (require-init 'init-javascript t) (require-init 'init-org t) (require-init 'init-python t) (require-init 'init-lisp t) (require-init 'init-yasnippet t) (require-init 'init-cc-mode t) (require-init 'init-linum-mode) (require-init 'init-git) (require-init 'init-gtags t) (require-init 'init-clipboard) (require-init 'init-ctags t) (require-init 'init-bbdb t) (require-init 'init-gnus t) (require-init 'init-lua-mode t) (require-init 'init-workgroups2 t) (require-init 'init-term-mode t) (require-init 'init-web-mode t) (require-init 'init-company t) (require-init 'init-chinese t) (require-init 'init-keyfreq t) (require-init 'init-httpd t) (require-init 'init-theme) (require-init 'init-essential) (require-init 'init-misc t) (require-init 'init-emacs-w3m t) (require-init 'init-shackle t) (require-init 'init-dired t) (require-init 'init-writting t) (require-init 'init-hydra) (require-init 'init-evil) (require-init 'init-ediff) (if my-disable-idle-timer nil (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir))) (require-init 'init-flymake t) (if (my-vc-merge-p) nil (setq custom-file (expand-file-name (concat my-emacs-d "custom-set-variables.el"))) (if (file-exists-p custom-file) (load custom-file t t)) (load (expand-file-name "~/.custom.el") t nil)))
  eval-buffer(#<buffer  *load*> nil "/home/yfc/.emacs.d/init.el" nil t)  ; Reading at buffer position 6035
  load-with-code-conversion("/home/yfc/.emacs.d/init.el" "/home/yfc/.emacs.d/init.el" t t)
  load("/home/yfc/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x157fb6e69529>) #f(compiled-function () #<bytecode 0x157fb6e69541>) t)
  command-line()
  normal-top-level()Debugger entered--Lisp error: (file-error "https://mirrors.163.com/elpa/melpa-stable/archive-..." "Not found")
  signal(file-error ("https://mirrors.163.com/elpa/melpa-stable/archive-..." "Not found"))
  package--with-response-buffer-1("https://mirrors.163.com/elpa/melpa-stable/" #f(compiled-function () #<bytecode 0x157fb7720641>) :file "archive-contents" :async nil :error-function #f(compiled-function () #<bytecode 0x157fb7720659>) :noerror nil)
  package--download-one-archive(("melpa-stable" . "https://mirrors.163.com/elpa/melpa-stable/") "archive-contents" nil)
  package--download-and-read-archives(nil)
  package-refresh-contents()
  (cond ((package-installed-p package min-version) t) ((or (assoc package package-archive-contents) no-refresh) (package-install package)) (t (package-refresh-contents) (require-package package min-version t)))
  require-package(async)
  eval-buffer(#<buffer  *load*-658824> nil "/home/yfc/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 8884
  load-with-code-conversion("/home/yfc/.emacs.d/lisp/init-elpa.el" "/home/yfc/.emacs.d/lisp/init-elpa.el" t t)
  load("/home/yfc/.emacs.d/lisp/init-elpa" t t)
  (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t))
  (if (or (not maybe-disabled) (not (my-vc-merge-p))) (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t)))
  require-init(init-elpa)
  (let* ((file-name-handler-alist nil)) (require-init 'init-autoload) (require-init 'init-modeline) (require-init 'init-utils) (require-init 'init-file-type) (require-init 'init-elpa) (if my-disable-idle-timer (progn (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir)))) (require-init 'init-spelling t) (require-init 'init-ibuffer t) (require-init 'init-ivy) (require-init 'init-windows) (require-init 'init-javascript t) (require-init 'init-org t) (require-init 'init-python t) (require-init 'init-lisp t) (require-init 'init-yasnippet t) (require-init 'init-cc-mode t) (require-init 'init-linum-mode) (require-init 'init-git) (require-init 'init-gtags t) (require-init 'init-clipboard) (require-init 'init-ctags t) (require-init 'init-bbdb t) (require-init 'init-gnus t) (require-init 'init-lua-mode t) (require-init 'init-workgroups2 t) (require-init 'init-term-mode t) (require-init 'init-web-mode t) (require-init 'init-company t) (require-init 'init-chinese t) (require-init 'init-keyfreq t) (require-init 'init-httpd t) (require-init 'init-theme) (require-init 'init-essential) (require-init 'init-misc t) (require-init 'init-emacs-w3m t) (require-init 'init-shackle t) (require-init 'init-dired t) (require-init 'init-writting t) (require-init 'init-hydra) (require-init 'init-evil) (require-init 'init-ediff) (if my-disable-idle-timer nil (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir))) (require-init 'init-flymake t) (if (my-vc-merge-p) nil (setq custom-file (expand-file-name (concat my-emacs-d "custom-set-variables.el"))) (if (file-exists-p custom-file) (load custom-file t t)) (load (expand-file-name "~/.custom.el") t nil)))
  eval-buffer(#<buffer  *load*> nil "/home/yfc/.emacs.d/init.el" nil t)  ; Reading at buffer position 6035
  load-with-code-conversion("/home/yfc/.emacs.d/init.el" "/home/yfc/.emacs.d/init.el" t t)
  load("/home/yfc/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x157fb6e69529>) #f(compiled-function () #<bytecode 0x157fb6e69541>) t)
  command-line()
  normal-top-level()

**Comment by redguardtoo** [comment] 2021-10-02 03:15
I tested on my machine. It's fine. Looks the 163 repo has some problem. Switch to melpa.org instead.

**Comment by sdetpearls** [comment] 2021-12-10 07:06
I had the same problem, and had tried tsinghua/163, also melpa.org behind a proxy.
BTW, I am using emacs in cygwin in an Windows 10 PC.

Here is the logs when starting emacs with '--debug-init'
`
Debugger entered--Lisp error: (error "nil/80 Name or service not known")
  signal(error ("nil/80 Name or service not known"))
  package--with-response-buffer-1("https://melpa.org/packages/" #f(compiled-function () #<bytecode 0x20026a18d>) :file "archive-contents" :async nil :error-function #f(compiled-function () #<bytecode 0x20026c6dd>) :noerror nil)
  package--download-one-archive(("melpa" . "https://melpa.org/packages/") "archive-contents" nil)
  package--download-and-read-archives(nil)
  package-refresh-contents()
  (if (or (assoc package package-archive-contents) no-refresh) nil (package-refresh-contents))
  (if (package-installed-p package min-version) nil (if (or (assoc package package-archive-contents) no-refresh) nil (package-refresh-contents)) (package-install package))
  require-package(async)
  eval-buffer(#<buffer  *load*-807154> nil "/home/admin/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 8928
  load-with-code-conversion("/home/admin/.emacs.d/lisp/init-elpa.el" "/home/admin/.emacs.d/lisp/init-elpa.el" t t)
  load("/home/admin/.emacs.d/lisp/init-elpa" t t)
  (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t))
  (if (or (not maybe-disabled) (not (my-vc-merge-p))) (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t)))
  require-init(init-elpa)
  (let* ((file-name-handler-alist nil)) (require-init 'init-autoload) (require-init 'init-modeline) (require-init 'init-utils) (require-init 'init-file-type) (require-init 'init-elpa) (if my-disable-idle-timer (progn (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir)))) (require-init 'init-spelling t) (require-init 'init-ibuffer t) (require-init 'init-ivy) (require-init 'init-windows) (require-init 'init-javascript t) (require-init 'init-org t) (require-init 'init-python t) (require-init 'init-lisp t) (require-init 'init-yasnippet t) (require-init 'init-cc-mode t) (require-init 'init-linum-mode) (require-init 'init-git) (require-init 'init-gtags t) (require-init 'init-clipboard) (require-init 'init-ctags t) (require-init 'init-bbdb t) (require-init 'init-gnus t) (require-init 'init-lua-mode t) (require-init 'init-workgroups2 t) (require-init 'init-term-mode t) (require-init 'init-web-mode t) (require-init 'init-company t) (require-init 'init-chinese t) (require-init 'init-keyfreq t) (require-init 'init-httpd t) (require-init 'init-theme) (require-init 'init-essential) (require-init 'init-misc t) (require-init 'init-emacs-w3m t) (require-init 'init-shackle t) (require-init 'init-dired t) (require-init 'init-writting t) (require-init 'init-hydra) (require-init 'init-evil) (require-init 'init-ediff) (if my-disable-idle-timer nil (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir))) (require-init 'init-flymake t) (if (my-vc-merge-p) nil (setq custom-file (expand-file-name (concat my-emacs-d "custom-set-variables.el"))) (if (file-exists-p custom-file) (load custom-file t t)) (load (expand-file-name "~/.custom.el") t nil)))
  eval-buffer(#<buffer  *load*> nil "/home/admin/.emacs.d/init.el" nil t)  ; Reading at buffer position 6100
  load-with-code-conversion("/home/admin/.emacs.d/init.el" "/home/admin/.emacs.d/init.el" t t)
  load("/home/admin/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x200176671>) #f(compiled-function () #<bytecode 0x200176689>) t)
  command-line()
  normal-top-level()
`

**Comment by redguardtoo** [comment] 2021-12-11 03:07
Looks like you failed to down `archive-contents` which is the list of packages.

Definitely networking problem. Try download packages from melpa. Use proxy if you have to.

**Comment by jackyzy823** [comment] 2021-12-14 15:24
FYI. I fixed this via  https://github.com/syl20bnr/spacemacs/issues/12535

> In ~/.emacs.d/init.el, at the top, I added (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")

However  i still need to comment out to due to `package is unavailable` error
```emacs
;(require-package 'gitignore-mode)
;(require-package 'gitconfig-mode)
;(require-package 'emms)
;(require-package 'nov)
```

**Comment by redguardtoo** [comment] 2021-12-15 09:08
Looks you're not using my latest `~/.emacs.d`

**Comment by atomsi** [comment] 2022-01-02 00:40
**same issues**
**envi:** centos 8.4
**log:**
(base) [tom@nuc ~]$ rm .emacs.* -rf
(base) [tom@nuc ~]$ git clone https://github.com/redguardtoo/emacs.d.git .emacs.d
Cloning into '.emacs.d'...
remote: Enumerating objects: 33485, done.
remote: Counting objects: 100% (711/711), done.
remote: Compressing objects: 100% (312/312), done.
remote: Total 33485 (delta 420), reused 621 (delta 373), pack-reused 32774
Receiving objects: 100% (33485/33485), 42.60 MiB | 10.45 MiB/s, done.
Resolving deltas: 100% (20179/20179), done.
(base) [tom@nuc ~]$ emacs 
**then get error messages in emacs:**
Warning (initialization): An error occurred while loading ‘/home/tom/.emacs.d/init.el’:

error: Package ‘async-’ is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

**Comment by redguardtoo** [comment] 2022-01-02 02:19
Try `emacs --debug-init`, what's output?

**Comment by Zexin-Li** [comment] 2022-01-11 12:11
我也遇到安装后第一次启动包无法下载的问题，期间尝试换清华和163的源，但换成spacemacs的配置同样换国内源不会下载不了。
通过emacs --debug-init启动输出如下
Debugger entered--Lisp error: (error "Could not create connection to elpa.gnu.org:443")
  signal(error ("Could not create connection to elpa.gnu.org:443"))
  package--with-response-buffer-1("https://elpa.gnu.org/packages/" #f(compiled-function () #$  package--download-one-archive(("gnu" . "https://elpa.gnu.org/packages/") "archive-contents$  package--download-and-read-archives(nil)
  package-refresh-contents()
  (if (or (assoc package package-archive-contents) no-refresh) nil (package-refresh-contents$  (if (package-installed-p package min-version) nil (if (or (assoc package package-archive-c$  require-package(async)
  eval-buffer(#<buffer  *load*-252706> nil "/home/lzx/.emacs.d/lisp/init-elpa.el" nil t)  ; $  load-with-code-conversion("/home/lzx/.emacs.d/lisp/init-elpa.el" "/home/lzx/.emacs.d/lisp/$  load("/home/lzx/.emacs.d/lisp/init-elpa" t t)
  (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t))
  (if (or (not maybe-disabled) (not (my-vc-merge-p))) (progn (load (file-truename (format "%$  require-init(init-elpa)
  (let* ((file-name-handler-alist nil)) (require-init 'init-autoload) (require-init 'init-mo$  eval-buffer(#<buffer  *load*> nil "/home/lzx/.emacs.d/init.el" nil t)  ; Reading at buffer$  load-with-code-conversion("/home/lzx/.emacs.d/init.el" "/home/lzx/.emacs.d/init.el" t t)
  load("/home/lzx/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x15798b94e0c9>) #f(compil$  command-line()
  normal-top-level()

**Comment by redguardtoo** [comment] 2022-01-12 01:59
`elpa.gnu.org`经常出问题。 我的配置默认是不连它的。我在知乎和微博已吐嘈过很多次GNU的网络服务的。
例如 https://zhuanlan.zhihu.com/p/72883715

如果我的配置有什么不同，一般都不是疏漏，而是为了解决问题而采取的解决方案。绝大多数人都觉得elpa.gnu.org是必须的，我对其是避而远之。

**Comment by Zexin-Li** [comment] 2022-01-12 05:47
我修改了init-elpa.el，在package-archives
`(setq package-archives
      '(
        ;; uncomment below line if you need use GNU ELPA
        ;; ("gnu" . "https://elpa.gnu.org/packages/")
        ;;("melpa" . "https://melpa.org/packages/")
        ;;("melpa-stable" . "https://stable.melpa.org/packages/")

        ;; Use either 163 or tsinghua mirror repository when official melpa
        ;; is slow or shutdown.

        ;; ;; {{ Option 1: 163 mirror repository:
        ;; ;; ("gnu" . "https://mirrors.163.com/elpa/gnu/")
         ("melpa" . "https://mirrors.163.com/elpa/melpa/")
         ("melpa-stable" . "https://mirrors.163.com/elpa/melpa-stable/")
        ;; ;; }}

        ;; ;; {{ Option 2: tsinghua mirror repository
        ;; ;; @see https://mirror.tuna.tsinghua.edu.cn/help/elpa/ on usage:
        ;; ;; ("gnu"   . "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
        ;; ("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")
        ;; ("melpa-stable" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa-stable/")
        ;; }}
        ))`
但还是会报错，输出如下
`Debugger entered--Lisp error: (error "Could not create connection to mirrors.163.com:443")
  signal(error ("Could not create connection to mirrors.163.com:443"))
  package--with-response-buffer-1("https://mirrors.163.com/elpa/melpa/" #f(compiled-function$  package--download-one-archive(("melpa" . "https://mirrors.163.com/elpa/melpa/") "archive-c$  package--download-and-read-archives(nil)
  package-refresh-contents()
  (if (or (assoc package package-archive-contents) no-refresh) nil (package-refresh-contents$  (if (package-installed-p package min-version) nil (if (or (assoc package package-archive-c$  require-package(async)
  eval-buffer(#<buffer  *load*-219631> nil "/home/lzx/.emacs.d/lisp/init-elpa.el" nil t)  ; $  load-with-code-conversion("/home/lzx/.emacs.d/lisp/init-elpa.el" "/home/lzx/.emacs.d/lisp/$  load("/home/lzx/.emacs.d/lisp/init-elpa" t t)
  (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t))
  (if (or (not maybe-disabled) (not (my-vc-merge-p))) (progn (load (file-truename (format "%$  require-init(init-elpa)
  (let* ((file-name-handler-alist nil)) (require-init 'init-autoload) (require-init 'init-mo$  eval-buffer(#<buffer  *load*> nil "/home/lzx/.emacs.d/init.el" nil t)  ; Reading at buffer$  load-with-code-conversion("/home/lzx/.emacs.d/init.el" "/home/lzx/.emacs.d/init.el" t t)
  load("/home/lzx/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1564473bd0c9>) #f(compil$  command-line()
  normal-top-level()`
会不会是我emacs版本问题，我用的自己编译的27.2版本最简单的
`./configure --with-x-toolkit=no --with-xpm=ifavailable --with-jpeg=ifavailable --with-png=ifavailable --with-gif=ifavailable --with-tiff=ifavailable --with-gnutls=ifavailable`
之前用apt下载的emacs26是没问题的

**Comment by Zexin-Li** [comment] 2022-01-12 05:48
我修改了init-elpa.el，在package-archives
`
(setq package-archives
      '(
        ;; uncomment below line if you need use GNU ELPA
        ;; ("gnu" . "https://elpa.gnu.org/packages/")
        ;;("melpa" . "https://melpa.org/packages/")
        ;;("melpa-stable" . "https://stable.melpa.org/packages/")

        ;; Use either 163 or tsinghua mirror repository when official melpa
        ;; is slow or shutdown.

        ;; ;; {{ Option 1: 163 mirror repository:
        ;; ;; ("gnu" . "https://mirrors.163.com/elpa/gnu/")
         ("melpa" . "https://mirrors.163.com/elpa/melpa/")
         ("melpa-stable" . "https://mirrors.163.com/elpa/melpa-stable/")
        ;; ;; }}

        ;; ;; {{ Option 2: tsinghua mirror repository
        ;; ;; @see https://mirror.tuna.tsinghua.edu.cn/help/elpa/ on usage:
        ;; ;; ("gnu"   . "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
        ;; ("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")
        ;; ("melpa-stable" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa-stable/")
        ;; }}
        ))
`
但还是会报错，输出如下
`
Debugger entered--Lisp error: (error "Could not create connection to mirrors.163.com:443")
  signal(error ("Could not create connection to mirrors.163.com:443"))
  package--with-response-buffer-1("https://mirrors.163.com/elpa/melpa/" #f(compiled-function$  package--download-one-archive(("melpa" . "https://mirrors.163.com/elpa/melpa/") "archive-c$  package--download-and-read-archives(nil)
  package-refresh-contents()
  (if (or (assoc package package-archive-contents) no-refresh) nil (package-refresh-contents$  (if (package-installed-p package min-version) nil (if (or (assoc package package-archive-c$  require-package(async)
  eval-buffer(#<buffer  *load*-219631> nil "/home/lzx/.emacs.d/lisp/init-elpa.el" nil t)  ; $  load-with-code-conversion("/home/lzx/.emacs.d/lisp/init-elpa.el" "/home/lzx/.emacs.d/lisp/$  load("/home/lzx/.emacs.d/lisp/init-elpa" t t)
  (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t))
  (if (or (not maybe-disabled) (not (my-vc-merge-p))) (progn (load (file-truename (format "%$  require-init(init-elpa)
  (let* ((file-name-handler-alist nil)) (require-init 'init-autoload) (require-init 'init-mo$  eval-buffer(#<buffer  *load*> nil "/home/lzx/.emacs.d/init.el" nil t)  ; Reading at buffer$  load-with-code-conversion("/home/lzx/.emacs.d/init.el" "/home/lzx/.emacs.d/init.el" t t)
  load("/home/lzx/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1564473bd0c9>) #f(compil$  command-line()
  normal-top-level()
`
会不会是我emacs版本问题，我用的自己编译的27.2版本最简单的
`./configure --with-x-toolkit=no --with-xpm=ifavailable --with-jpeg=ifavailable --with-png=ifavailable --with-gif=ifavailable --with-tiff=ifavailable --with-gnutls=ifavailable`
之前用apt下载的emacs26是没问题的

**Comment by redguardtoo** [comment] 2022-01-12 07:24
`--with-gnutls=ifavailable` 这不能是可选的吧。必须得有才能连https协议的仓库啊。

**Closed** 2022-03-08 13:53 UTC
